config/routes.rb
Rails.application.routes.draw do
  root 'interventions#new'
  resources :interventions, only: %i[new create deletion]

  get 'calendars/availabilities' => 'calendars#availabilities'

  namespace :admin do
    root 'calendars#index'
    resources :calendars do
      resources :openings
    end
    resources :appointments
    resources :interventions
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  # Associations
  has_many :interventions
  has_many :openings
  has_many :appointments

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :intervals, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def availabilities intervention
    params = {
      openings: self.openings,
      appointments: self.appointments,
      interval: self.intervals,
      duration: intervention.duration
    }
    my_planning = PlanningFiller.new(params)
    my_planning.make_my_planning
    my_planning.green_spots.inspect
    return my_planning.all_free_starting
  end

end

app/controllers/admin/calendars_controller.rb
class Admin::CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to [:admin, @calendar], notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to [:admin, @calendar], notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to admin_calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:name)
    end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  before_action :set_calendar, only: [:availabilities]

  def show
  end

  def availabilities
    intervention = @calendar.interventions.find_by_id(params[:intervention_id])
    availabilities = @calendar.availabilities(intervention)
    respond_to do |format|
      format.json { render availabilities }
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :intervention_ids %><br>
    <%= collection_check_boxes(
      :calendar, :intervention_ids, Intervention.all, :id, :name)
     %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calendars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.name %></td>
        <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
        <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar', new_calendar_path %>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>