config/routes.rb
Rails.application.routes.draw do
  root 'interventions#new'
  resources :interventions, only: %i[new create deletion]

  get 'calendars/availabilities' => 'calendars#availabilities'

  namespace :admin do
    root 'calendars#index'
    resources :calendars do
      resources :openings
    end
    resources :appointments
    resources :interventions
  end
end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
  # Associations
  belongs_to :calendar

  # Validations
  validates :name, presence: true
  validates :duration, presence: true, inclusion: 1..60
end

app/controllers/admin/interventions_controller.rb
class Admin::InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]

  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions
  # POST /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to [:admin, @intervention], notice: 'Intervention was successfully created.' }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to [:admin, @intervention], notice: 'Intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to admin_interventions_url, notice: 'Intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intervention_params
      params.require(:intervention).permit(:name, :duration, :price, :calendar_id)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_for(@intervention) do |f| %>
  <% if @intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% @intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :calendar_id %><br>
    <%= f.select(
        :calendar_id,
        options_from_collection_for_select(
          Calendar.all,
          :id,
          :name,
          f.object.calendar_id
        )
    ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interventions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Price</th>
      <th>Calendar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.name %></td>
        <td><%= intervention.duration %></td>
        <td><%= intervention.price %></td>
        <td><%= intervention.calendar.name %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form' %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intervention.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @intervention.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @intervention.price %>
</p>

<p>
  <strong>Calendar:</strong>
  <%= @intervention.calendar_id %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>